# Generated by Django 5.2.7 on 2026-01-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_phone_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_landlord',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_tenant',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
