# Generated by Django 5.2.7 on 2026-02-24 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_bookingmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lock_in_months',
            field=models.PositiveIntegerField(default=0, help_text='Number of months tenant agrees not to exit early.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('terminated', 'Terminated')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EarlyExitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('desired_move_out', models.DateField()),
                ('notice_given_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('owner_approved', 'Owner Approved'), ('owner_rejected', 'Owner Rejected'), ('inspection_scheduled', 'Inspection Scheduled'), ('inspection_completed', 'Inspection Completed'), ('settlement_confirmed', 'Settlement Confirmed'), ('lease_terminated', 'Lease Terminated'), ('disputed', 'Disputed')], db_index=True, default='requested', max_length=30)),
                ('owner_response_date', models.DateTimeField(blank=True, null=True)),
                ('owner_comments', models.TextField(blank=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='early_exit', to='listings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('damage_assessed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exit_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='listings.earlyexitrequest')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_payable_to_owner', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_refund_to_tenant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('tenant_accepted', 'Tenant Accepted'), ('owner_accepted', 'Owner Accepted'), ('disputed', 'Disputed'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('exit_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='listings.earlyexitrequest')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.booking')),
            ],
        ),
    ]
