# Generated by Django 5.2.7 on 2026-02-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_inspectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Decimal degrees', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Decimal degrees', null=True),
        ),
    ]
