# Generated by Django 5.2.7 on 2026-02-24 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_property_image_propertyimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation (if cancelled)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When landlord finalized the booking (rented_out)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rented_out', 'Rented Out'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary property image (upload at least one image)', null=True, upload_to='property_images/'),
        ),
        migrations.CreateModel(
            name='PropertyAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Date of appointment')),
                ('appointment_time', models.TimeField(help_text='Preferred time of appointment')),
                ('message', models.TextField(blank=True, help_text='Additional message/questions for landlord')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('landlord_notes', models.TextField(blank=True, help_text="Landlord's response/notes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='listings.booking')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='listings.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
                'indexes': [models.Index(fields=['property', 'status'], name='listings_pr_propert_1da329_idx'), models.Index(fields=['tenant', 'appointment_date'], name='listings_pr_tenant__b5b09d_idx')],
            },
        ),
    ]
