# Generated by Django 5.2.7 on 2026-04-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_booking_cancellation_reason_booking_finalized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
    ]
