# Generated by Django 5.2.7 on 2026-04-22 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_settlement_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='owner_receipt_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='owner_receipt_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='tenant_payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='settlement_proofs/'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='tenant_payment_reference',
            field=models.CharField(blank=True, help_text='UPI/bank reference (optional).', max_length=120),
        ),
        migrations.AddField(
            model_name='settlement',
            name='tenant_payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_tenant', to=settings.AUTH_USER_MODEL),
        ),
    ]
